name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.1.0
      with:
        node-version: '12.x'
        
    - name: Install
      run: npm ci
        
    - name: Lint
      run: npm run lint
      
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.1.0
      with:
        node-version: '12.x'
        
    - name: Install
      run: npm ci
        
    - name: Build
      run: npm run build
        
    - name: Test
      run: npm test
      
  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.1.0
      with:
        node-version: '12.x'
        
    - name: Publish to npm
      uses: pascalgn/npm-publish-action@1.2.0
      with:
        tag_name: "v%s"
        tag_message: "v%s"
        commit_pattern: "^\\[CD\\] Release v(\\S+)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}