name: CI/CD

on:
  push:
    branches: [ master, dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.4.2
      with:
        node-version: '12.x'
        
    - name: Install
      run: npm ci
        
    - name: Lint
      run: npm run lint
        
    - name: Lint Tests
      run: npm run lint-tests
      
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.4.2
      with:
        node-version: '12.x'
        
    - name: Install
      run: npm ci
        
    - name: Build
      run: npm run build
        
    - name: Test
      run: npm test
      
  publish-if-version-changed:
    needs: ["lint", "build-and-test"]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.4.2
      with:
        node-version: '12.x'
        
    - name: Install
      run: npm ci
        
    - name: Publish to npm
      id: publish
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
        
    - if: steps.publish.type == 'none'
      name: "Version hasn't changed, no new package published!"
      run: |
        echo "Version hasn't changed, no new package published!"
        
    - if: steps.publish.type != 'none'
      name: "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
      run: |
        echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"